### PR TITLE
Added Get Step Count From Google Fit Api

### PR DESCRIPTION
**Pull request by heertheeswaran**
1. Gets the step count from google fit for the day

### CODE REVIEW

**Comment by heertheeswaran** [comment]
@harshareddy794 Can you merge this?

**Comment by heertheeswaran** [comment]
@harshareddy794 Any idea when this will be merged?

**Comment by harshareddy794** [comment]
@heertheeswaran  Because of a lot of open PRs approval and merging of PRs will take some time.
It will be approved in a day or two. Hope you understand

**Review by harshareddy794 — APPROVED** [review]
That's really awsome @heertheeswaran 
Thanks for your contribution to open source community

**Pull request merged**
