### PR TITLE
Length of longest common subsequence between 2 strings

### PR DESCRIPTION
**Pull request by sarthak-1503**

### CODE REVIEW

**Review by harshareddy794 — APPROVED** [review]
That's cool @sarthak-1503 
Thanks, for your contribution

**Comment by sarthak-1503** [comment]
Thanks

**Comment by sarthak-1503** [comment]
@harshareddy794 Please add "hacktoberfest-accepted" label on my merged pull request #112

**Comment by harshareddy794** [comment]
@sarthak-1503 I have added hacktoberfest as a topic. It is counted towards contribution to hacktoberfest

**Comment by sarthak-1503** [comment]
@harshareddy794 ok

**Pull request merged**
