### PR TITLE
Added binarySearch.c in the C folder of the repository

### PR DESCRIPTION
**Pull request by sarthak-1503**

### CODE REVIEW

**Review by harshareddy794 — APPROVED** [review]
That's a good contribution @sarthak-1503

**Comment by sarthak-1503** [comment]
@harshareddy794 Thank you!!

**Comment by sarthak-1503** [comment]
@harshareddy794 Please add "hacktoberfest-accepted" label to my merged pull request #133

**Comment by harshareddy794** [comment]
@sarthak-1503 I have added hacktoberfest as a topic. It is counted towards contribution to hacktoberfest

**Comment by sarthak-1503** [comment]
@harshareddy794 ok

**Pull request merged**
